kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dotnet8-hello-ci
  labels:
    app: dotnet8-hello
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
  volumeMode: Filesystem