apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/deployment.yaml
  - ./manifests/service.yaml

commonLabels:
  app: dotnet8-hello
  app.kubernetes.io/part-of: dotnet-apps
  app.kubernetes.io/managed-by: kustomize